### ISSUE TITLE
Change PoiString Test to PoiString-master

### ISSUE THREAD

**Issue by Jaredy00** [officialpoiuytrewq4645/PoiString#1]

**Comment by Jaredy00** [comment]
Could not locate file"\PoiString Test\PoiString Test.csproj"

**Comment by Jaredy00** [comment]
also second file is called PoiString.csproj not PoiString Test.csproj

**Comment by officialpoiuytrewq4645** [comment]
not exactly, poistring test is my test file, the sln thinks its there but its not because i excluded it
